import 'package:documentation_builder/parser/link_parser.dart';
import 'package:flutter_test/flutter_test.dart';

import 'link_parser_test.dart';

main() {
  test('examples.mdt',() async {
    var rootNode=await LinkParser().parse(
        TestRootNode("The [DocumentationBuilder]s own documentation was generated by itself and also serves as show case."

            "You can view the templates files and the generated output on https://github.com and https://pub.dev:"

            "- README"
            "  - [GitHub suffix='/blob/main/doc/templates/README.mdt' title='Markdown Template File']"
            "  - [GitHub suffix='/blob/main/README.md' title='Generated Markdown File']"
            "  - [PubDev title='Generated Markdown Page']"
            "- CHANGELOG"
            "  - [GitHub suffix='/blob/main/doc/templates/CHANGELOG.mdt' title='Markdown Template File']"
            "  - [GitHub suffix='/blob/main/CHANGELOG.md' title='Generated Markdown File']"
            "  - [PubDevProjectVersions title='Generated Markdown Page']"
            "  - Wiki pages"
            "  - [GitHub suffix='/blob/main/doc/templates' title='Markdown Template Files']"
            "  - [GitHub suffix='/blob/main/doc/wiki title='Generated Markdown Files']"
            "  - [GitHubWiki title='Generated Markdown Pages']"
            "  - example"
            "  - [GitHub suffix='/blob/main/doc/templates/example.mdt' title='Markdown Template File']"
            "  - [GitHub suffix='/blob/main/example/example.md' title='Generated Markdown File']"
            "  - [PubDev title='Generated Markdown Page']"
        ));
    expect(rootNode.children.length,1);
  });
}