targets:
  $default:
    sources:
      - doc/**
      - lib/**
      - test/**
    builders:
      documentation_builder|markdown_template_builder:
        enabled: True
      documentation_builder|output_builder:
        enabled: True

builders:
  markdown_template_builder:
    import: 'package:documentation_builder/builders/builder_factory.dart'
    builder_factories: ['markdownTemplateBuilder']
    build_extensions:
      .*: # Note that this is ignored because its overridden by the Builder.buildExtensions method
        - .dummy # Note that this is ignored because its overridden by the Builder.buildExtensions method
    build_to: cache
    auto_apply: root_package
    runs_before: [documentation_builder|documentation_builder]
  output_builder:
    import: 'package:documentation_builder/builders/builder_factory.dart'
    builder_factories: ['outputBuilder']
    build_extensions:
      .*: # Note that this is ignored because its overridden by the Builder.buildExtensions method
        - .dummy # Note that this is ignored because its overridden by the Builder.buildExtensions method
    build_to: source
    auto_apply: root_package
