# Read about `build.yaml` at https://pub.dev/packages/build_config
      
builders:
  documentation_builder:
    import: 'package:documentation_builder/builder.dart'
    builder_factories: [ 'documentationBuilder' ]
    build_extensions: {"doc/template/{{fileName}}.mdt": ["{{fileName}}.md"]}
    build_to: source
    auto_apply: dependents