# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      - doc/**
      - lib/**
      - bin/**
      - test/**
      - pubspec.*
      - $package$
    builders:
      documentation_builder|documentation_builder:
        enabled: True
      
builders:
  documentation_builder:
    import: 'package:documentation_builder/builder.dart'
    builder_factories: [ 'documentationBuilder' ]
    build_extensions: {"doc/template/{{fileName}}.mdt": ["{{fileName}}.md"]}
    build_to: source
    auto_apply: dependents