targets:
  $default:
    sources:
      - $package$
      - doc/**
      - lib/**
      - test/**
    builders:
      documentation_builder|template_builder:
        enabled: True
      documentation_builder|parse_builder:
        enabled: True
      documentation_builder|output_builder:
        enabled: True

builders:
  template_builder:
    import: 'package:documentation_builder/builder/builder_factory.dart'
    builder_factories: ['markdownTemplateBuilder']
    build_extensions:
      .*: # Note that this is ignored because its overridden by the Builder.buildExtensions method
        - .dummy # Note that this is ignored because its overridden by the Builder.buildExtensions method
    build_to: cache
    auto_apply: root_package
    runs_before: [documentation_builder|parse_builder]
  parse_builder:
    import: 'package:documentation_builder/builder/builder_factory.dart'
    builder_factories: [ 'parseBuilder' ]
    build_extensions:
      .*: # Note that this is ignored because its overridden by the Builder.buildExtensions method
        - .dummy # Note that this is ignored because its overridden by the Builder.buildExtensions method
    build_to: source
    auto_apply: root_package
    runs_before: [documentation_builder|output_builder]
  output_builder:
    import: 'package:documentation_builder/builder/builder_factory.dart'
    builder_factories: ['outputBuilder']
    build_extensions:
      .*: # Note that this is ignored because its overridden by the Builder.buildExtensions method
        - .dummy # Note that this is ignored because its overridden by the Builder.buildExtensions method
    build_to: source
    auto_apply: root_package
